### ISSUE TITLE
Warn Meldung nach js-controller Test 3.0.4

### ISSUE THREAD

**Issue by sigi2345** [Mic-M/ioBroker.logparser#12]
Meldung nach js-controller Test 3.0.4

`logparser.0 2020-04-08 23:31:40.041 warn (13012) This value will not be set in future versions. Please report this to the developer.
logparser.0 2020-04-08 23:31:40.041 warn (13012) State value to set is invalid for logparser.0.visualization.table0.selection: The state is missing the required property val!
logparser.0 2020-04-08 23:31:09.748 warn (13012) This value will not be set in future versions. Please report this to the developer.
logparser.0 2020-04-08 23:31:09.747 warn (13012) State value to set is invalid for logparser.0.visualization.table0.selection: The state is missing the required property val!`

**Comment by Mic-M** [comment]
Danke für den Test Sigi. Sollte behoben sein mit Version 0.4.2.
