### ISSUE TITLE
Enhancement : Automatically add entries for all adapter

### ISSUE THREAD

**Issue by DutchmanNL** [Mic-M/ioBroker.logparser#2]
It would be more easier if filters for already installed adapter are automatically adopted to the configuration screen.
This avoids mistakes and ensures all adapter are visible tracet.

Enabling should be optionale to decide by User if the adapter should be filtered or part of global info.

**Comment by Mic-M** [comment]
Thanks. 
I wasn't aware of this use case, as users of the [log script](https://github.com/Mic-M/iobroker.logfile-script) (me included) used it for parsing logs of multiple adapters, but not necessarily each individual one separately.
Anyway, this is a great suggestion. 
Regarding implementation: How about a button in the adapter admin settings like "Add filter rule for each adapter". Then, the adapter populates the filter table in the settings accordingly.

**Comment by DutchmanNL** [comment]
> How about a button in the adapter admin settings like "Add filter rule for each adapter". Then, the adapter populates the filter table in the settings accordingly.

Cool suggestion yes do you can also control it.

That button should check if entry’s are already in or need to be added

Yea I think the use case is more from a developer perspective.
For me, having 11 (more coming) build and in maintenance it’s not only for showing logs but also troubleshooting an Analyse of Beta Tests

That last thing I assume was not thought about it yet, hey that’s why we put heads together

I really like this adapter, use case :

Sourceanalytix can produce in Info or debug Mode hundreds of log entry’s depending on your setup

To troubleshoot user and myself, I know use this adapter and I am very happy with it!

**Comment by DutchmanNL** [comment]
i assume this will not be handled after a year. so we can close ?
