### ISSUE TITLE
No translation, all in German 

### ISSUE THREAD

**Issue by DutchmanNL** [Mic-M/ioBroker.logparser#3]
Interfaces should follow the ioBroker setup ensuring all values are in English and translated by the word.js library.

This can be done completely automatically by using gulp, please let me know if you need assistance for that

**Comment by Mic-M** [comment]
Thanks. I will certainly have to update the admin/index_html and words.js files. 
I am labelling this as bug, since this needs to be fixed before the adapter can be added to the latest repository.

**Comment by DutchmanNL** [comment]
Do you need help ? I could 

- do the current translations for you and provide a PR
OR (maybe better)
- make one, show you how to do it and you can learn and do it yourself

Remember I use gulp for this, so all translations are automated not every language manually ;)

**Comment by Mic-M** [comment]
Yes, I need help :-) thanks! In my other adapter windows-control, I have done this manually in index_html and words.js. So I'd prefer the second option so I can learn.

Having this done automatically sounds pretty cool, so every help is very appreciated.

**Comment by DutchmanNL** [comment]
> Yes, I need help :-) thanks! In my other adapter windows-control, I have done this manually in index_html and words.js. So I'd prefer the second option so I can learn.
> 
> Having this done automatically sounds pretty cool, so every help is very appreciated.

sure I will help you out and make something as an example.
If you want feel free to contact me by telegram = @RaffiDuck

**Comment by DutchmanNL** [comment]
pull request send including instructions

**Comment by Mic-M** [comment]
Again. thanks a bunch DutchmanNL! Due to your great help and pull request https://github.com/Mic-M/ioBroker.logparser/pull/9 I was able to fully implement. The translation through gulp is pretty cool.

**Comment by DutchmanNL** [comment]
👍 :)
