### ISSUE TITLE
Different states for different warn levels

### ISSUE THREAD

**Issue by DutchmanNL** [Mic-M/ioBroker.logparser#4]
Current situation : 

Log level can be chosen for the specific entry, all types of log levels enter in 1 data point.

Wanted situation :

Seperate date points for Info,Warn,Error etc and make this configurable.
So you choose what kind of logging the filter should apply on and an option if this should be in separated states

It helps to only log Error related data in a specific datapoint

**Comment by Mic-M** [comment]
Thanks.
I can certainly implement this. However, in consideration of issue #2 – let's say you have 40 adapters, with 4 log levels (debug, info, warn, error) = 160 different json logs. Isn't this too much to handle for the user? (and maybe for small servers like Raspi).
Goal of this adapter was to apply regexp etc. and filter, in order to not have so many different states, but rather having an overview of like certain warn and errors, or of certain device changes (like: door/window states log, etc.).

What is your use case for this?

**Comment by DutchmanNL** [comment]
> I can certainly implement this. However, in consideration of issue #2 – let's say you have 40 adapters, with 4 log levels (debug, info, warn, error) = 160 different json logs. Isn't this too much to handle for the user? (and maybe for small servers like Raspi).

hmm... interesting thought dude! 
Ok lets brainstorm and go back to the "why" should I want this.

My use case is : 

- quick overview of attention points
- easy access to the data were needed

Having said that, splitting the JSON does fulfill this demand in generic but is one way to do it.
I would say just clouting the type of error could be enough as long I have a chance to see it.

Example : I use this adapter, it indicates 3 error's for adapter xxx

now I want to see the errors, but about of logs is limited to 10 and the error was 14 messages back....
Now I miss the important information.


so lets turn the use case : and think in a scenario : the adapter is not only parsing, but providing me a trigger for attention.

**Comment by Mic-M** [comment]
>Example : I use this adapter, it indicates 3 error's for adapter xxx
now I want to see the errors, but history of logs is limited to 10 and the error was 14 messages back....
Now I miss the important information.

Got it. Now with this use case it makes very much sense to me as well.

> so lets turn the use case and think in a scenario : the adapter is not only parsing, but providing me a trigger for attention.
Actually an awesome idea to simplifying error "handling". We just need to figure out what would be the best way to implement.
Now regarding issue #2 - probably it would be better to let the user choose which adapters to add to the filter (so multiple selection by using the ctrl key)....

**Comment by DutchmanNL** [comment]
> Now regarding issue #2 - probably it would be better to let the user choose which adapters to add to the filter (so multiple selection by using the ctrl key)....

definitly :), as mentioned in #2 the most important thing is to not type the names but have a kind of search and auto - add functionality also for this use cases 

The can call this "goldplating" but its adding a lot of value to the adapter and the benefit of the already current version is that all "detailed" log levels are configurable by state.
So the end-user should ensure using the proper settings but most of we talk here are "advanced" options

**Comment by DutchmanNL** [comment]
as this I issue is open for a year, I assume it. can be closed and not implemented ?
